name: Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecución diaria
  workflow_dispatch:      # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: cano0102  # ¡Cambia por tu usuario!
          svg_path: assets/github-contribution-grid-snake.svg

      - name: Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push
